#pragma once

#define SCREEN_WIDTH 1024
#define SCREEN_HEIGHT 768
#define SCREEN_BPP 16
// GILSON: #define SCREEN_FLAGS SDL_ANYFORMAT | SDL_FULLSCREEN | SDL_DOUBLEBUF | SDL_NOFRAME
#define SCREEN_FLAGS SDL_ANYFORMAT | SDL_DOUBLEBUF 
